# Generated by Django 3.1.3 on 2020-11-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(default='mainImg.jpg', upload_to='photos/main_photo/%Y/%m/%d/')),
                ('sq', models.FloatField(default='1', max_length=4, verbose_name='Площадь')),
                ('stage', models.IntegerField(default='1', verbose_name='Этаж')),
                ('bathroom', models.IntegerField(default='1', verbose_name='Ванная комната')),
                ('rooms', models.IntegerField(default='1', verbose_name='Комнаты')),
                ('price', models.IntegerField(default='1', verbose_name='Цена')),
                ('deal', models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], default='R', max_length=4, verbose_name='Сделка')),
                ('province', models.CharField(choices=[('Barcelona', 'Barcelona'), ('Girona', 'Girona'), ('Lleida', 'Lleida'), ('Tarragona', 'Tarragona')], default='Barcelona', max_length=100, verbose_name='Провинция')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
