# Generated by Django 3.1 on 2020-11-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201106_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='img',
            field=models.ImageField(blank=True, upload_to='photos/main_photo/%Y/%m/%d/'),
        ),
    ]
