# Generated by Django 3.1 on 2020-11-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201109_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/secondary_photo/%Y/%m/%d/')),
                ('property_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.property')),
            ],
        ),
    ]
