# Generated by Django 3.1 on 2020-11-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20201111_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimages',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='photos/secondary_photo/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='image_es',
            field=models.ImageField(blank=True, null=True, upload_to='photos/secondary_photo/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='photos/secondary_photo/%Y/%m/%d/'),
        ),
    ]
