# Generated by Django 3.1 on 2020-11-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20201114_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='property',
            name='title_es',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='property',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='photos/secondary_photo/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='image_es',
            field=models.ImageField(blank=True, null=True, upload_to='photos/secondary_photo/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='photos/secondary_photo/%Y/%m/%d/'),
        ),
    ]
