# Generated by Django 3.1 on 2020-11-14 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20201114_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='propertyimages',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='propertyimages',
            name='image_es',
        ),
        migrations.RemoveField(
            model_name='propertyimages',
            name='image_ru',
        ),
    ]
