# Generated by Django 3.1 on 2020-11-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20201122_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathroom',
            field=models.IntegerField(default='1', verbose_name='Bathroom'),
        ),
        migrations.AlterField(
            model_name='property',
            name='deal',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], default='R', max_length=4, verbose_name='Deal'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='img',
            field=models.ImageField(blank=True, upload_to='photos/main_photo/%Y/%m/%d/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(default='1', verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='province',
            field=models.CharField(choices=[('Barcelona', 'Barcelona'), ('Girona', 'Girona'), ('Lleida', 'Lleida'), ('Tarragona', 'Tarragona')], default='Barcelona', max_length=100, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(default='1', verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sq',
            field=models.FloatField(default='1', max_length=4, verbose_name='Square'),
        ),
        migrations.AlterField(
            model_name='property',
            name='stage',
            field=models.IntegerField(default='1', verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/secondary_photo/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
