# Generated by Django 3.1 on 2020-11-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20201125_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='deal',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Rent'), (2, 'Sale')], default=1, verbose_name='Deal'),
        ),
    ]
