# Generated by Django 3.1 on 2020-11-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20201125_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deal_en',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], default='Rent', max_length=4, null=True, verbose_name='Deal'),
        ),
        migrations.AddField(
            model_name='property',
            name='deal_es',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], default='Rent', max_length=4, null=True, verbose_name='Deal'),
        ),
        migrations.AddField(
            model_name='property',
            name='deal_ru',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], default='Rent', max_length=4, null=True, verbose_name='Deal'),
        ),
    ]
