# Generated by Django 3.1 on 2020-11-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20201125_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='deal_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='deal_es',
        ),
        migrations.RemoveField(
            model_name='property',
            name='deal_ru',
        ),
    ]
