# Generated by Django 3.1 on 2020-11-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20201125_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='deal',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], default='rent', max_length=4, verbose_name='Deal'),
        ),
    ]
