# Generated by Django 3.1 on 2020-11-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20201125_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='deal',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], default='Rent', max_length=4, verbose_name='Deal'),
        ),
    ]
