# Generated by Django 3.1 on 2020-11-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20201125_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='deal',
            field=models.CharField(choices=[(None, 'CHECK'), ('Rent', 'RENT'), ('Sale', 'SALE')], max_length=14, verbose_name='Deal'),
        ),
    ]
