# Generated by Django 3.1 on 2020-11-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20201125_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='photos/avatar/%Y/%m/%d/', verbose_name='Avatar')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Name')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('citizen', models.CharField(blank=True, max_length=150, verbose_name='Citizen')),
            ],
        ),
    ]
