# Generated by Django 3.1 on 2020-11-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='citizen',
        ),
        migrations.AddField(
            model_name='feedback',
            name='city',
            field=models.CharField(blank=True, max_length=150, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='country',
            field=models.CharField(blank=True, max_length=150, verbose_name='Country'),
        ),
    ]
