# Generated by Django 3.1 on 2020-12-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20201130_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='city_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='city_es',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='city_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='country_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='country_es',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='country_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_en',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_es',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name_es',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Name'),
        ),
    ]
