# Generated by Django 3.1 on 2020-12-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_auto_20201201_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='deal',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], default='RENT', max_length=14, verbose_name='Deal'),
        ),
    ]
