# Generated by Django 3.1 on 2020-12-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_auto_20201207_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='deal',
            field=models.CharField(choices=[('', 'Choose'), ('Rent', 'Rent'), ('Sale', 'Sale')], default='RENT', max_length=14, verbose_name='Deal'),
        ),
        migrations.AlterField(
            model_name='property',
            name='province',
            field=models.CharField(choices=[('', 'Choose'), ('Barcelona', 'Barcelona'), ('Girona', 'Girona'), ('Lleida', 'Lleida'), ('Tarragona', 'Tarragona')], default='Barcelona', max_length=100, verbose_name='Province'),
        ),
    ]
