# Generated by Django 3.1 on 2020-12-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_auto_20201212_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='deal',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], default='Rent', max_length=14, verbose_name='Deal'),
        ),
    ]
