# Generated by Django 3.1 on 2020-12-22 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_auto_20201218_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbacksImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/feedback/%Y/%m/%d/', verbose_name='Image')),
                ('feedback_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.feedback')),
            ],
        ),
    ]
