# Generated by Django 3.1 on 2020-12-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_feedbacksimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbacksImages',
            new_name='FeedbackImages',
        ),
    ]
