# Generated by Django 3.1 on 2021-01-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_auto_20201222_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reformed',
            field=models.CharField(blank=True, max_length=150, verbose_name='Reformed'),
        ),
    ]
