# Generated by Django 3.1 on 2021-01-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_feedback_reformed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reformed_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Reformed'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reformed_es',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Reformed'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reformed_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Reformed'),
        ),
    ]
